config/routes.rb
OpenFarm::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
      registrations: "registrations",
      confirmations: "confirmations"
    }

  scope '(:locale)', locale: /en|nl/ do
    root to: 'homes#show'
    post '(:locale)/crop_search' => 'crop_searches#search',
         as: :crop_search_via_post
    get '(:locale)/crop_search' => 'crop_searches#search',
        as: :crop_search_via_get

    devise_scope :users do
      get 'users/gardens' => 'users#gardens'
      get 'users/finish' => 'users#finish'
      get 'users/edit' => 'users#edit'
      put 'users' => 'users#update'
    end
    resources :users
    resources :crops
    resources :guides
    resources :stages
    resources :requirements
    resources :gardens
  end

  get 'announcements/hide', to: 'announcements#hide'

  namespace :api, defaults: {format: 'json'} do
    get '/aws/s3_access_token' => 'aws#s3_access_token'
    post '/local/upload_file' => 'file_upload#upload_file'

    namespace :v1 do
      get '/progress/pictures/:obj_type/:obj_id' => 'progress_job#show'

      resources :crops, only: [:create, :index, :show, :update] do
        resources :pictures, only: [:index, :show]
      end
      resources :tags, only: :index do
        collection do
          get '/:query', action: :index
        end
      end
      resources :guides, only: [:create, :show, :update, :destroy]
      resources :users, only: [:show, :update] do
        resources :gardens, only: [:index]
        resources :compatibility_score, only: [:show]
      end
      resources :gardens, only: [:create, :show, :update, :destroy] do
        resources :garden_crops, only: [:index,
                                        :show,
                                        :create,
                                        :update,
                                        :destroy]
      end
      resources :detail_options, only: [:index]
      resources :stage_options, only: [:index]
      resources :stage_action_options, only: [:index]
      resources :stages, only: [:create, :show, :update, :destroy] do
        resources :pictures,
                  only: [:index],
                  controller: 'stages',
                  action: 'pictures'
        resources :stage_actions,
                  only: [:index, :destroy]
                  # controller: 'stages',
                  # action: 'stage_actions'
      end

      resources :tokens, path: 'token', only: [:create] do
        collection do
          delete :destroy
        end
      end
    end
  end

  get '/:locale' => 'homes#show'
end

app/models/guide.rb
# frozen_string_literal: true

class Guide
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Slug
  include Mongoid::Timestamps

  attr_accessor :current_user_compatibility_score

  searchkick(callbacks: :async)

  # The below seems to have made no difference, but it's based on:
  # https://github.com/ankane/searchkick#stay-synced
  # and the recommendations here:
  # https://github.com/ankane/searchkick/issues/373#issuecomment-71967887
  # Though it can probably be tweaked further.
  scope :search_import, -> { includes(:user) }

  #   We need to override `impresionsist`s default behavior of
  #   `dependent: :delete_all`.
  #   If we don't, tests will fail with the following error:
  #   NameError uninitialized constant Mongoid::Relations::Cascading::DeleteAll
  # has_many :impressions, as: :impressionable, dependent: :delete

  # NOTE TO FUTURE SELF: Try removing the line above and see if tests pass.
  #   that would indicate that the bug was fixed upstream and we can remove this
  #   hotfix.
  field :impressions_field, default: 0, type: Integer

  belongs_to :crop, counter_cache: true
  belongs_to :user
  has_many :stages

  field :draft, type: Boolean, default: true

  embeds_one :time_span, cascade_callbacks: true, as: :timed

  field :name
  field :location
  field :overview
  field :practices, type: Array
  field :completeness_score, default: 0
  field :popularity_score, default: 0, type: Integer

  field :times_favorited, type: Integer, default: 0

  validates_presence_of :crop, :name

  field :processing_pictures, type: Integer, default: 0
  embeds_many :pictures, cascade_callbacks: true, as: :photographic
  accepts_nested_attributes_for :pictures

  # Points to the index of images which should
  # be the featured image
  field :featured_image, type: Integer

  slug :name, history: true

  after_save :calculate_completeness_score
  # Maybe Popularity Score should be updated more frequently?
  after_save :calculate_popularity_score

  accepts_nested_attributes_for :time_span

  def self.sorted_for_user(guides, user)
    # PRODUCTION IS DOWN RIGHT NOW.
    # I am going to plug this runtime error until
    # we figure out what went wrong during the
    # Elastic upgrade - RC 2 MAR 2019

    if user
      guides =
        guides.sort_by do |guide|
          guide.compatibility_score(user)
          guide.current_user_compatibility_score = guide.compatibility_score(user)
          guide.current_user_compatibility_score
        end
      guides.reverse
    else
      guides
    end
  end

  def owned_by?(current_user)
    !!(current_user && user == current_user)
  end

  def search_data
    as_json only: %i[name overview crop_id draft compatibilities]
    # We changed this to as_json ^ because it was causing weird nesting.
    # Not sure that this should be a problem though, it's been filed:
    # https://github.com/ankane/searchkick/issues/595

    # {
    #   name: name,
    #   overview: overview,
    #   crop_id: crop_id,
    #   draft: draft,
    #   compatibilities: compatibilities
    # }
  end

  def compatibilities
    return @compatibilities if defined?(@compatibilities)

    @compatibilities = []

    User.includes(:gardens).each do |user|
      @compatibilities << { user_id: user.id.to_s, score: compatibility_score(user).to_i }
    end

    @compatibilities
  end

  def basic_needs(current_user)
    return nil unless current_user
    return nil if current_user.gardens.blank?

    first_garden = current_user.gardens.first

    # We should probably store these in the DB
    basic_needs = [
      {
        name: 'Sun / Shade',
        slug: 'sun-shade',
        overlap: [],
        total: [],
        percent: 0,
        user: first_garden.average_sun,
        garden: first_garden.name
      },
      {
        name: 'Location',
        slug: 'location',
        overlap: [],
        total: [],
        percent: 0,
        user: first_garden.type,
        garden: first_garden.name
      },
      {
        name: 'Soil Type',
        slug: 'soil',
        overlap: [],
        total: [],
        percent: 0,
        user: first_garden.soil_type,
        garden: first_garden.name
      },
      {
        name: 'Practices',
        slug: 'practices',
        overlap: [],
        total: [],
        percent: 0,
        user: first_garden.growing_practices,
        garden: first_garden.name
      }
    ]

    # Still have to implement:
    # pH Range, Temperature, Water Use, Practices,
    # Time Commitment, Physical Ability, Time of Year

    find_overlap_in basic_needs
  end

  def compatibility_score(current_user)
    return current_user_compatibility_score if current_user_compatibility_score

    return nil unless current_user
    return nil if current_user.gardens.blank?

    count = 0

    sum =
      basic_needs(current_user).inject(0) do |memo, n|
        count += 1
        n[:percent] ? memo + n[:percent] : memo
      end

    (sum.to_f / count * 100).round
  end

  def compatibility_label(current_user)
    if current_user_compatibility_score
      score = current_user_compatibility_score
    else
      score = compatibility_score(current_user)
    end

    if score.nil?
      return ''
    elsif score > 75
      return 'high'
    elsif score > 50
      return 'medium'
    else
      return 'low'
    end
  end

  protected

  # TODO: Fairly simplistic. This should be expanded to somehow take into
  # consideration stages and selected practices
  def calculate_completeness_score
    total = 0.0
    counted = 0.0
    fields.keys.each do |key|
      total += 1
      counted += 1 if self[key]
    end

    write_attributes(completeness_score: counted / total)
  end

  # TODO: Fairly simplistic. Should probably be normalized properly.
  # Right now normalization is based on the highest impressions, and how
  # this one stacks up. It should probably also take into consideration
  # How many gardens this thing is in.
  def calculate_popularity_score
    top_guide = (Guide.order_by('impressions_field' => :asc).last)
    at_most = (top_guide.impressions_field || 0).to_i
    normalized = impressions_field.to_f / at_most
    write_attributes(popularity_score: normalized)
  end

  private

  # For each stage, find the overlapping needs,
  # and then calculate the percentage overlap of each need
  # ToDO this can be cleaned up, probably significantly
  # by externalizing the basic_need structure.
  def find_overlap_in(basic_needs)
    stages.each do |stage|
      basic_needs.each do |need|
        if # This is bad structure
         need[
           :name
         ] ==
           'Sun / Shade'
          build_overlap_and_total need, stage.light
        end
        build_overlap_and_total need, stage.environment if need[:name] == 'Location'
        build_overlap_and_total need, stage.soil if need[:name] == 'Soil Type'
      end
    end

    calculate_percents basic_needs
  end

  def build_overlap_and_total(need_hash, stage_req)
    if stage_req
      new_array = stage_req.select { |req| req == need_hash[:user] }
      need_hash[:overlap] += new_array
      need_hash[:total] = need_hash[:total] + stage_req
    end
  end

  def calculate_percents(basic_needs)
    basic_needs.each do |need|
      if need[:total] && !need[:total].blank?
        need[:percent] = need[:overlap].size.to_f / need[:total].size
      else
        need[:percent] = 0
      end
      # Compress the total array now that we don't need it's length
      need[:total].uniq!
    end
  end
end

app/controllers/api/v1/guides_controller.rb
# frozen_string_literal: true

class Api::V1::GuidesController < Api::V1::BaseController
  skip_before_action :authenticate_from_token!, only: %i[index show]

  def create
    # According to JSON-API Params must be structured like this:
    # {
    #  'data': {
    #     'type': 'guides',
    #     'id': '<id>',
    #     'attributes': {},
    # }
    @outcome =
      Guides::CreateGuide.run(
        raw_params[:data],
        crop_id: raw_params[:data][:crop_id], crop_name: raw_params[:data][:crop_name], user: current_user
      )
    respond_with_mutation(:created, include: %w[stages stages.pictures stages.stage_actions crop pictures user])
  end

  def show
    guide = Guide.find(raw_params[:id])
    render json: serialize_model(guide, include: %w[stages stages.pictures stages.stage_actions crop pictures user])
  end

  def update
    # According to JSON-API Params must be structured like this:
    # {
    #  'data': {
    #     'type': 'guides',
    #     'id': '<id>',
    #     'attributes': {},
    # }
    @outcome =
      Guides::UpdateGuide.run(
        { attributes: {} },
        raw_params[:data],
        user: current_user, guide: Guide.find(raw_params[:id])
      )
    respond_with_mutation(:ok, include: %w[stages stages.pictures stages.stage_actions crop pictures user])
  end

  def destroy
    @outcome = Guides::DestroyGuide.run(raw_params, user: current_user)
    respond_with_mutation(:no_content)
  end
end

app/controllers/guides_controller.rb
# frozen_string_literal: true

class GuidesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    if current_user
      redirect_to user_path(current_user)
    else
      redirect_to root_path
    end
  end

  def show
    @guide = Guide.find(params[:id])
  end

  def new
    @guide = Guide.new
  end

  def edit
    @guide = Guide.find(params[:id])

    # if not @guide.user.id == current_user.id
    redirect_to @guide
    # end
  end

  def destroy
    @outcome = Guides::DestroyGuide.run(raw_params, user: current_user)
    redirect_to guides_path
  end
end

app/views/guides/show/_guide_controllers.html.erb
<div class="guide-controls">
  <% if @guide.owned_by?(current_user) %>
    <a ng-hide="editing"
      class="button tiny secondary edit-link"
      ng-click="toggleEditingGuide()">
      <%= icon('fa', 'edit') %> Edit Guide Basics
    </a>
    <a ng-show="editing"
      class="button tiny primary edit-link"
      ng-click="saveGuideChanges()">
      <%= icon('fa', 'save') %> Save Changes
    </a>
    <%= link_to(icon('fa', 'trash') + ' ' + t('.delete_guide'), guide_path(@guide), method: 'delete', class: 'button tiny secondary edit-link', data: {confirm: "Are you sure?"}) %>
  <% end %>
  <a type="button" id="print" class="button tiny secondary edit-link" onclick="print()"><%= icon('fa', 'print') + ' ' + t('.print_guide') %></a>
  <a type="button" id="favorite" class="button tiny secondary edit-link" ng-class="{ favorite : inFavorites }" ng-click="favoriteGuide(guide.id)">
    <i class="fa fa-star"
      ng-class="{'fa-spin':updatingFavoritedGuides}"></i>
    <%= t('.favorite') %>
  </a>
  <button href="#"
          dropdown-toggle="#share"
          aria-controls="share"
          aria-expanded="false"
          class="button tiny secondary dropdown">Share
  </button>
  <br>
  <ul id="share"
      class="f-dropdown"
      aria-hidden="true"
      tabindex="-1">
    <li>
      <a href="#"
         socialshare
         socialshare-provider="facebook"
         socialshare-title="<%= @guide.name %>"
         socialshare-media="<%= (@guide.featured_image && @guide.featured_image.image_url) || @guide.crop.main_image_path({:medium => true}) %>"
         socialshare-url="<%= guide_url(@guide) %>">
        Facebook
      </a>
    </li>
    <li>
      <a href="#"
         socialshare
         socialshare-provider="twitter"
         socialshare-text="<%= @guide.name %>"
         socialshare-via="OpenFarmCC"
         socialshare-hashtags="farming,opensource"
         socialshare-url="<%= guide_url(@guide) %>">
        Twitter
      </a>
    </li>
    <li>
      <a href="#"
         socialshare
         socialshare-provider="email"
         socialshare-subject="<%= @guide.name %>"
         socialshare-body="We thought you'd like these instructions on how to grow <%= @guide.crop.name %>: <%= guide_url(@guide) %>">
        Email
      </a>
    </li>
  </ul>
</div>

app/views/guides/show/_show_guide_basic_needs.html.erb
<accordion-group
  ng-init="r.isopen = true"
  is-open="r.isopen"
  class="accordion-navigation basic-needs">
  <accordion-heading class="title-wrapper">
    <h2 class="title" id="basic-needs">
      <%= t('.title') %>
      <i class="right" ng-class="{'fa fa-angle-down': true, 'open': r.isopen}"></i>
    </h2>
  </accordion-heading>
  <div class="row">
    <div ng-if="guide.basic_needs.length"
         class="columns small-12 actual-basic-needs">
      <table>
        <tbody>
          <tr ng-repeat="basicNeed in guide.basic_needs" class="basic-need"
              ng-class="{ 'medium' : basicNeed.percent >= .5 && basicNeed.percent < .75, 'high': basicNeed.percent >= .75, 'low' : basicNeed.percent < .5 }"
              ng-if="basicNeed.total && basicNeed.overlap"
              tooltip="{{ basicNeed.tooltip }}"
              >

            <!-- TODO: icons -->
            <td class="basic-need-name">
              <p class="icon {{ 'of-' + basicNeed.slug }}"><span ng-bind="basicNeed.name"></span></p>
            </td>
            <td class="basic-need-value">
              <p ng-bind="basicNeed.total"></p>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="small-12 columns empty"
      ng-if="guide.basic_needs.length === 0">
      <i class="fa fa-thumbs-down"></i>
      <br/>
      <%= t('.no_basic_needs_yet') %>
    </div>
  </div>

</accordion-group>

app/views/guides/show/_show_guide_overview.html.erb
<h4 class="title" id="overview">
  <%= t('.overview') %>
</h4>

<p ng-show="!editing && practicesList().length > 0">
  This guide uses {{ practicesList() }} practices.
</p>
<p ng-show="!editing && practicesList().length === 0">
  This guide has listed no specific practices.
</p>

<div multi-row-select
     ng-show="editing"
     class="multi-choice"
     options-array="practices"
     multi-select-overflow-count="3"
     multi-select-type="checkbox"
     multi-select-id="practices">
</div>
<br/>

<div class="markdown"
  markdown="guide.overview"
  ng-hide="editing">
</div>
<div ng-show="!editing && !guide.overview">
  The author of this guide hasn't given an overview of it yet.
</div>

<textarea
  ng-model="guide.overview"
  ng-show="editing">
</textarea>

<span ng-model="guide.location"
      location
      ng-show="editing"
      name="location"
      loading-text="<%= t('application.loading_locations') %>">
</span>

<em ng-if="guide.location">In:</em> <span ng-bind="guide.location">
</span>

<of-images-upload
  ng-show="editing"
  single="true"
  class="upload-stage-picture"
  item="guide"
  images-key="'pictures'"
  item-type="'guide'">
</of-images-upload>

app/views/guides/show/_show_guide_stages.html.erb
<accordion-group
  ng-init="stage.isopen = true"
  is-open="stage.isopen"
  class="accordion-navigation stages">
  <accordion-heading class="title-wrapper">
    <h2 class="title" id="stages">
      <%= t('.title') %>
      <i class="right" ng-class="{'fa fa-angle-down': true, 'open': stage.isopen}"></i>
    </h2>
  </accordion-heading>
  <div class="box"
    ng-if="guide.stages.length === 0">
    <div class="row">
      <div class="small-12 columns empty">
        <i class="fa fa-thumbs-down"></i>
        <br/>
        <%= t('.no_stages_yet') %>
      </div>
    </div>
  </div>
  <tabset class="tabs stages"
    of-sticky
    of-sticky-child=".tabs"
    of-sticky-offset="70">

    <tab ng-repeat="stage in guide.stages | orderBy:'order'">
      <tab-heading href="#instructions-{{ stage.slug }}" class="tab-heading">
        <h3>{{ stage.name }}</h3>
      </tab-heading>

      <div of-show-guide-stages
        stage="stage"
        can-edit="currentUser.id === guide.user.id"
        trigger-guide-update="guideUpdate"
        detail-options="options"
        class="columns small-12"
        s3-bucket="'<%= ENV['S3_BUCKET_NAME'] %>'">

      </div>
    </tab><tab class="add-stage" heading="+ Add New Stages" ng-if="currentUser.id === guide.user.id">
      <div of-show-add-stage-to-guide
        existing-stages="guide.stages"
        guide-id="guide.id">
      </div>
    </tab>
  </tabset>
</accordion-group>

app/views/guides/show/_show_guide_statistics.html.erb
<accordion-group
  ng-init="stat.isopen = true"
  is-open="stat.isopen"
  class="accordion-navigation statistics">
  <accordion-heading class="title-wrapper">
    <h2 class="title" id="statistics">
      <%= t('.title') %>
      <i class="right" ng-class="{'fa fa-angle-down': true, 'open': stat.isopen}"></i>
    </h2>
  </accordion-heading>
  <p class="section-text">
    <div class="box">
      <div class="row">
        <div class="empty columns large-12 large-centered">

           <i class="fa fa-bar-chart-o"></i><br/>
            <%= t('.once_we_know_more') %>
         </div>
       </div>
    </div>

  </p>
</accordion-group>

app/views/guides/show/_show_guide_timeline.html.erb
<accordion-group
  ng-init="timeline.isopen = true"
  is-open="timeline.isopen"
  class="accordion-navigation timeline">
  <accordion-heading class="title-wrapper">
    <h2 class="title" id="timeline">
      <%= t('.title') %>
      <i class="right" ng-class="{'fa fa-angle-down': true, 'open': timeline.isopen}"></i>
    </h2>
  </accordion-heading>
  <p class="section-text">
    <div class="box">
      <div class="row" ng-if="haveTimes.length === 0">
        <div class="empty columns large-12 large-centered">
          <i class="fa fa-clock-o"></i><br/>
          <%= t('.not_supplied_timeline_info') %>
        </div>
      </div>
      <div class="row" ng-if="haveTimes.length > 0">
        <div class="timeline-box large-12 columns large-centered" timeline>
        </div>
      </div>
    </div>

  </p>
</accordion-group>