config/routes.rb
OpenFarm::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
      registrations: "registrations",
      confirmations: "confirmations"
    }

  scope '(:locale)', locale: /en|nl/ do
    root to: 'homes#show'
    post '(:locale)/crop_search' => 'crop_searches#search',
         as: :crop_search_via_post
    get '(:locale)/crop_search' => 'crop_searches#search',
        as: :crop_search_via_get

    devise_scope :users do
      get 'users/gardens' => 'users#gardens'
      get 'users/finish' => 'users#finish'
      get 'users/edit' => 'users#edit'
      put 'users' => 'users#update'
    end
    resources :users
    resources :crops
    resources :guides
    resources :stages
    resources :requirements
    resources :gardens
  end

  get 'announcements/hide', to: 'announcements#hide'

  namespace :api, defaults: {format: 'json'} do
    get '/aws/s3_access_token' => 'aws#s3_access_token'
    post '/local/upload_file' => 'file_upload#upload_file'

    namespace :v1 do
      get '/progress/pictures/:obj_type/:obj_id' => 'progress_job#show'

      resources :crops, only: [:create, :index, :show, :update] do
        resources :pictures, only: [:index, :show]
      end
      resources :tags, only: :index do
        collection do
          get '/:query', action: :index
        end
      end
      resources :guides, only: [:create, :show, :update, :destroy]
      resources :users, only: [:show, :update] do
        resources :gardens, only: [:index]
        resources :compatibility_score, only: [:show]
      end
      resources :gardens, only: [:create, :show, :update, :destroy] do
        resources :garden_crops, only: [:index,
                                        :show,
                                        :create,
                                        :update,
                                        :destroy]
      end
      resources :detail_options, only: [:index]
      resources :stage_options, only: [:index]
      resources :stage_action_options, only: [:index]
      resources :stages, only: [:create, :show, :update, :destroy] do
        resources :pictures,
                  only: [:index],
                  controller: 'stages',
                  action: 'pictures'
        resources :stage_actions,
                  only: [:index, :destroy]
                  # controller: 'stages',
                  # action: 'stage_actions'
      end

      resources :tokens, path: 'token', only: [:create] do
        collection do
          delete :destroy
        end
      end
    end
  end

  get '/:locale' => 'homes#show'
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :guides
  has_many :gardens

  has_and_belongs_to_many :favorited_guides, class_name: 'Guide', inverse_of: nil

  has_one :token, dependent: :delete
  has_one :user_setting
  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  field :display_name, type: String
  validates_presence_of :display_name
  NO_TOS = 'to the Terms of Service and Privacy Policy'
  field :agree, type: Boolean
  validates :agree, acceptance: { accept: true, message: NO_TOS }, on: :create

  field :mailing_list, type: Mongoid::Boolean, default: false
  field :help_list, type: Mongoid::Boolean, default: false

  field :admin, type: Mongoid::Boolean, default: false

  # Privacy fields
  field :is_private, type: Mongoid::Boolean, default: false
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  # These are needed to be defined. Dunno why this doesn't
  # get automatically generated. Part of Devise.Confirmable
  # http://stackoverflow.com/a/9952241/154392
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String

  has_merit

  after_save :create_garden_if_none

  def user_setting
    UserSetting.find_or_create_by(user: self)
  end

  def has_filled_required_settings?
    user_setting.location.present? && user_setting.units.present?
  end

  def favorite_crop_image_from_user_setting
    user_setting.favorite_crop_image
  end

  protected

  def confirmation_required?
    false
  end

  private

  def create_garden_if_none
    if self.gardens.all.count == 0 && self.confirmed?
      Gardens::CreateGarden.run(
        user: self,
        attributes: { is_private: true,
                      name: I18n::t('registrations.your_first_garden') }
      )
    end
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < Api::V1::BaseController
  skip_before_action :authenticate_from_token!, only: %i[show]

  def gardens_index
    render json: serialize_models(User.find(raw_params[:id]).gardens, include: %w[garden_crops pictures])
  end

  def compatibility_score(user_id, id)
    user = User.find(user_id)
    render json: Guide.find(id).compatibility_score(user)
  end

  def show
    user = User.find(raw_params[:id])
    if Pundit.policy(current_user, user).show?
      render json: serialize_model(user, include: %w[user_setting guides favorited_guides])
    else
      raise OpenfarmErrors::NotAuthorized
    end
  end

  def update
    @outcome =
      Users::UpdateUser.run(
        attributes: raw_params[:data],
        current_user: current_user,
        pictures: raw_params[:data][:pictures],
        user_setting: raw_params[:data][:user_setting],
        id: "#{current_user._id}"
      )

    respond_with_mutation(:ok, include: %w[user_setting guides favorited_guides])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: %i[index finish gardens]

  def update
    authorize current_user

    user_settings = { units: raw_params[:units], location: raw_params[:location] }
    @outcome =
      Users::UpdateUser.run(
        attributes: raw_params,
        current_user: current_user,
        user_setting: user_settings,
        pictures: raw_params[:pictures],
        id: "#{current_user._id}"
      )

    if @outcome.errors
      flash[:alert] = @outcome.errors.message_list
      redirect_to(controller: 'users', action: 'finish')
    else
      redirect_to user_path(current_user)
    end
  end

  def show
    @user = User.find(raw_params[:id])
    authorize @user
  end

  def index
    @users = policy_scope(User)
  end

  def edit
    authorize current_user
  end

  def finish
    authorize current_user
  end

  def gardens
    @gardens = current_user.gardens
    redirect_to user_path(current_user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def list_gardens_on_show?
    has_non_default_garden?(@user) || authorized_for?(@user)
  end

  def has_non_default_garden?(user)
    user.gardens.each { |garden| return true unless garden.user_default?}

    false
  end

  def authorized_for?(user)
    user == current_user && current_user.confirmed?
  end
end

app/views/users/_gardens.html.erb
<div class="section-header">
  <h3 class="section-title">Gardens</h3>
  <!-- TODO: Only show button if user is current_user. This will replace the more confusing add garden foo we currently have -->
  <button class="button right tiny">Add Garden</button>
</div>

<div class="gardens" ng-controller="gardenCtrl" ng-cloak>
  <div alerts ng-model="alerts"></div>
  <div ng-if="!currentUser" class="row">
    <div class="columns small-6 small-centered loading-content">
      <i class="fa fa-spinner fa-spin"></i> <%= t('.loading_your_gardens') %>
    </div>
  </div>
  <div class="garden" ng-repeat="garden in currentUser.gardens" ng-cloak ng-show="!garden.hide">
    <div class="row header">
      <% if params[:manage] %>
        <div class="columns large-6 large-centered">
          <%= t('.first_garden_html') %>
        </div>
      <% end %>
      <div class="columns large-9">
        <h2>
          <span ng-bind="garden.name" ng-if="!garden.editing"></span>
          <label ng-if="garden.editing"><%= t('.garden_name') %></label><input type="text" ng-model="garden.name" ng-if="garden.editing"/>
        </h2>
      </div>
      <div class="columns large-3 edit">
        <i class="fa fa-lock"></i>
        <a class="button secondary tiny"
           ng-click="garden.editing = !garden.editing"
           ng-show="!garden.editing"><i class="fa fa-edit"></i> <%= t('.edit_garden') %></a>
        <a class="button secondary tiny"
           ng-click="garden.editing = !garden.editing; saveGarden(garden)"
           ng-show="garden.editing"><i class="fa fa-save"></i> <%= t('.save_garden') %></a>
        <a class="button secondary tiny"
           ng-click="destroyGarden($index, garden)"
           ng-show="garden.editing"><i class="fa fa-trash"></i> <%= t('.destroy_garden') %></a>
      </div>
    </div>
    <div class="row info">
      <div class="columns large-4">
        <p ng-if="garden.editing">
          <%= t('.upload_picture') %>
        </p>
        <span ng-repeat="pic in garden.pictures"
              class="thumbnails"
              ng-class="{ 'deleted' : pic.deleted }"
              ng-if="garden.editing || !pic.deleted"
              ng-init="pic.deleted = false"
              ng-click="pic.deleted = !pic.deleted">
          <img ng-src="{{ pic.thumbnail_url || pic.image_url }}"
               ng-model="pic"/>
        </span>
        <div s3-upload
            bucket="'<%= ENV['S3_BUCKET_NAME'] %>'"
            ng-if="garden.editing"
            ng-model="s3upload"
            s3-upload-place-pic="handleNewGardenImage(garden, image)"
            s3-upload-options="{getOptionsUri: '/api/aws/s3_access_token', folder: 'temp/'}">
        </div>
      </div>
      <div class="columns large-8">
        <div class="description markdown"
             markdown="garden.description"
             ng-if="!garden.editing">
        </div>
        <textarea ng-if="garden.editing"
                  ng-model="garden.description">
        </textarea>
        <table class="details">
          <tr>
            <th>
              <%= t('.garden_type') %>
            </th>
            <td>
              <span ng-bind="garden.type"
                    ng-if="!garden.editing">
              </span>
             <%# TODO: This should probably be
                 based on something stored in the
                 backend %>
              <select ng-if="garden.editing"
                      ng-model="garden.type">
                <option value="Outside"><%= t('.outside') %></option>
                <option value="Inside"><%= t('.inside') %></option>
                <option value="Greenhouse"><%= t('.greenhouse') %></option>
              </select>
            </td>
          </tr>
          <tr>
            <th>
              <%= t('.sunlight') %>
            </th>
            <td>
              <span ng-bind="garden.average_sun"
                    ng-if="!garden.editing">
              </span>
              <%# TODO: This should probably be
                  based on something stored in the
                  backend %>
              <select ng-if="garden.editing"
                      ng-model="garden.average_sun">
                <option value="Full Sun"><%= t('.full_sun') %></option>
                <option value="Partial Sun"><%= t('.partial_sun') %></option>
                <option value="Full Shade"><%= t('.full_shade') %></option>
              </select>
            </td>
          </tr>
          <tr>
            <th>
              <%= t('.soil_type') %>
            </th>
            <td>
              <span ng-bind="garden.soil_type"
                    ng-if="!garden.editing">
              </span>
              <%# TODO: This should probably be
                  based on something stored in the
                  backend %>
              <select ng-if="garden.editing"
                      ng-model="garden.soil_type">
                <option value="Potting"><%= t('.potting') %></option>
                <option value="Loam"><%= t('.loam') %></option>
                <option value="Loamy Sand"><%= t('.loamy_sand') %></option>
                <option value="Sandy Clay"><%= t('.sandy_clay') %></option>
                <option value="Sandy Loam"><%= t('.sandy_loam') %></option>
                <option value="Clay Loam"><%= t('.clay_loam') %></option>
                <option value="Sandy Clay Loam"><%= t('.sandy_clay_loam') %></option>
                <option value="Sand"><%= t('.sand') %></option>
                <option value="Clay"><%= t('.clay') %></option>
                <option value="Silty Clay"><%= t('.silty_clay') %></option>
                <option value="Silty Clay Loam"><%= t('.silty_clay_loam') %></option>
                <option value="Silt Loam"><%= t('.silt_loam') %></option>
                <option value="Silt"><%= t('.silt') %></option>
              </select>
            </td>
          </tr>
          <tr>
            <th>
              <%= t('.ph') %>
            </th>
            <td>
              <span ng-bind="garden.ph" class="ph">
              </span>
              <input type="range"
                   min="0"
                   max="15"
                   step=".5"
                   ng-model="garden.ph"
                   ng-if="garden.editing"
                   />
            </td>
          </tr>
          <!-- <tr>
            <th>
              Growing Practices
            </th>
            <td>
            <span ng-bind="garden.growing_practices"
                  ng-if="!garden.editing">
            </span>
            </td>
          </tr> -->
        </table>
      </div>
    </div>
    <div class="row edit-buttons"
         ng-show="garden.selected">
      <div class="columns large-3 right">
        <a type="button"
           ng-show="!garden.editing_crops"
           class="button secondary tiny"
           ng-init="garden.editing_crops = false"
           ng-click="garden.editing_crops = !garden.editing_crops"
        ><i class="fa fa-edit"></i> <%= t('.edit') %></a>
        <a type="button"
           ng-show="garden.editing_crops"
           class="button secondary tiny"
           ng-click="garden.editing_crops = !garden.editing_crops; saveGardenCropChanges(garden);"
        ><i class="fa fa-save"></i> <%= t('.save_changes') %></a>
        <input type="button" value="Delete" class="button alert tiny" ng-click="deleteSelected(garden)"/>
      </div>
    </div>
    <div class="row crops">
      <div class="columns large-12">
        <table>
          <tr>
            <td>
              <input type="checkbox"
                     ng-model="garden.selectAll"
                     ng-change="selectAll(garden)"
                     ng-disabled="garden.editing_crops"/>
            </td>
            <th>
              <%= t('application.crop') %>
            </th>
            <th>
              <%= t('application.guide') %>
            </th>
            <th>
              <%= t('.sowed') %>
            </th>
            <th>
              <%= t('.life_stage') %>
            </th>
            <th>
              <%= t('.quantity') %>
            </th>
          </tr>
          <tr ng-repeat="crop in garden.garden_crops"
              ng-init="crop.hide = false"
              ng-hide="crop.hide">

            <td>
              <input type="checkbox"
                     ng-model="crop.selected"
                     ng-change="checkSelected(garden)"
                     ng-disabled="crop.selected && garden.editing_crops"
                     />
            </td>
            <td>
              <span ng-bind="crop.crop.name || crop.guide.crop.name">
              </span>
            </td>
            <td>
              <span ng-bind="crop.guide.name">
              </span>
            </td>
            <td>
              <span ng-bind="crop.sowed|date:'yyyy-MM-dd'"
                    ng-if="!(crop.selected && garden.editing)">
              </span>
              <input type="date"
                     ng-model="crop.sowed"
                     ng-if="crop.selected && garden.editing_crops"
                     />
            </td>
            <td>
              <span ng-bind="crop.stage"
                    ng-if="!(crop.selected && garden.editing_crops)">
              </span>
              <input type="text"
                     ng-model="crop.stage"
                     ng-if="crop.selected && garden.editing_crops"/>

            </td>
            <td>
              <span ng-bind="crop.quantity"
                    ng-show="!(crop.selected && garden.editing_crops)">
              </span>
              <input type="number"
                     ng-model="crop.quantity"
                     ng-show="crop.selected && garden.editing_crops"/>
            </td>
          </tr>
          <tr>
            <td colspan="6">
              <%= t('.add_crop') %>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <div class="add-garden row">
    <hr/>
    <div class="columns small-6"
         ng-class="{ 'small-centered' : currentUser.gardens.length === 0 }">
      <h4 ng-if="currentUser.gardens.length === 0">
        <%= t('.create_your_first_garden') %>
      </h4>
      <h4 ng-if="currentUser.gardens.length > 0">
        <%= t('.create_a_new_garden') %>
      </h4>
      <label><%= t('.call_your_garden') %></label>
      <input type="text" ng-model="newGarden.name"/>
      <input type="button"
             class="button"
             ng-cloak
             value="{{ currentUser.gardens.length === 0 ? '<%= t('.create_your_first_garden') %>' : '<%= t('.create_another_garden') %>' }}"
             ng-click="createGarden(newGarden);"/>
    </div>
  </div>
</div>
<% content_for(:end_js) do %>
  <%= javascript_tag "var USER_ID = '#{current_user._id}';" %>
  <%= javascript_include_tag 'users/gardens' %>
<% end %>

app/views/users/_guides.html.erb
<div class="section-header">
  <h3 class="section-title"><%= t('member.guides') %></h3>
  <!-- TODO: Only show create button if user is current_user -->
  <button class="button right tiny create-guide-button"><%= link_to t('application.create_guide'), new_guide_path %>
</div>

<div class="guides row guides-list">
  <div class="small-12 columns">
    <table>
      <% @user.guides.each do |guide| %>
        <tr>
          <td>
            <%= render partial:'/guides/compatibility_circle', locals:{guide: guide} %>
            <%= link_to(guide.name, { :controller => 'guides', :action => 'show', :id => guide.id}, :class => 'action show guide-name') %>
          </td>
          <td>
            <%= link_to(guide.crop.name, { controller: 'crops',
              action: 'show',
              id: guide.crop.id }, :class => 'action show crop-name') %>
          </td>
          <td>
            <%= link_to(icon('edit'), { :controller => 'guides', :action => 'edit', :id => guide.id}, :class => 'action show') %>
          </td>
          <td>
            <%= link_to(icon('trash'), guide_path(guide), :method => 'delete', :class => 'action show', data: {confirm: "Are you sure?"}) %>
          </td>
        </tr>
      <% end %>
    </table>
    <% if @user.guides.count == 0 %>
      <div class="loading-content">
        <%= t('.no_guides_yet') %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for(:start_js) do %>
  <%= javascript_include_tag '//maps.google.com/maps/api/js?key=' + ENV['GOOGLE_MAPS_API_KEY'] %>
<% end %>

<div class="finish"

  ng-controller="finishCtrl">
  <div class="row title">
    <div class="large-12 columns">
      <h2><%= t('.edit_profile') %></h2>
    </div>
  </div>
<%# form_for :user, controller: 'users', action: 'finish', method: 'put' do |f| %>
<form>
  <div class="row">
    <div class="large-4 columns">
      <label for="location">
        <%= t('users.finish.where_do_you_farm') %>
      </label>
      <small><%= t('users.finish.city_or_zip') %></small>
    </div>
    <div class="large-8 columns">
      <span location
            ng-model="user.user_setting.location"
            loading-text="<%= t('application.loading_locations') %>">
      </span>
    </div>
  </div>
  <div class="row">
    <div class="large-4 columns">
      <label for="units_preference">
        <%= t('users.finish.units_preference') %>
      </label>
    </div>
    <div class="large-8 columns">
      <input type="radio" id="units-imperial" value="imperial" name="units" ng-model="user.user_setting.units"><label for="units-imperial">Imperial</label>

      <input id="units-metric" type="radio" value="metric" name="units" ng-model="user.user_setting.units" checked><label for="units-metric">Metric</label>
    </div>
  </div>

  <div class="row">
      <div class="columns large-4">
        <label for="user[images]">Choose a profile image!</label>
      </div>
      <div class="columns large-8">
        <of-images-upload
          class="columns small-8 medium-8"
          item="user.user_setting"
          single="true"
          images-key="'pictures'"
          item-type="'user_setting'">
        </of-images-upload>
      </div>
    </div>


  <div class="row">
    <div class="large-4 columns">
      <label for="location">
        <%= t('users.finish.email_sign_up') %>
      </label>
    </div>
    <div class="large-8 columns">
      <input type="radio" id="yes-email" value="true" name="mailing_list" ng-checked="user.mailing_list" ><label for="yes-email">Yes</label>
      <input id="no-email" type="radio" value="false" name="mailing_list" checked ng-checked="!user.mailing_list"><label for="no-email">No</label>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <label for="help_sign_up">
        <%= t('.help_sign_up') %>
        <br/><small><%= t('users.finish.help_description') %></small>
      </label>

    </div>
    <div class="large-8 columns">
      <input type="radio" id="yes-help" value="true" name="help_list" ng-checked="user.help_list" ><label for="yes-help">Yes</label>
      <input id="no-help" type="radio" value="false" name="help_list" ng-checked="!user.help_list" checked><label for="no-help">No</label>
    </div>
  </div>

  <div class="row submit">
    <div class="large-12 columns">
    <span class="right">
      <i ng-if="user.sending"
        class="fa fa-spinner fa-spin loading-button"></i>
      <input class="button small"
        ng-disabled="user.sending"
        data-disable-with="Saving..."
        name="commit"
        type="submit"
        ng-click="submitForm()"
        value="<%= t('.save') %>"/>
      </span>
    </div>
  </div>
</form>
<%# end %>
</div>

<% content_for(:end_js) do %>
  <%= javascript_tag "var USER_ID = '#{current_user ? current_user.id : nil}';" %>
  <%= javascript_include_tag 'users/finish' %>
<% end %>

app/views/users/index.html.erb
<div class="row users-list">
  <div class="small-12 columns">
    <h2><%= t '.users' %></h2>
    <table>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to(user.display_name, {:action => 'show', :id => user.id}, :class=>'action show') %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <div class="row">
      <div class="large-8 medium-10 small-12 small-centered columns">
        <h1>Hey there stranger</h1>
        <%= render 'shared/user_form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= content_for(:title) do %>
  <%= @user.display_name %> Profile
<% end %>

<%= content_for(:social_image) do %>
  <%= @user.favorite_crop_image_from_user_setting && image_url(@user.favorite_crop_image_from_user_setting) %>
<% end %>

<div loader
  ng-show="ofPageLoading">
  <i class="fa fa-spinner fa-spin"></i>
</div>

<div class="member-profile"
  ng-controller="profileCtrl"
  ng-show="profileUser.user_setting !== undefined"
  ng-cloak>
  <!-- Pull cover image from member's favorite_crop -->

  <div class="row wide-row canopy-wrapper"
       style="background-image: url({{ profileUser.user_setting.favorite_crop.image_url || '/assets/baren_field.jpg' }}) ">
    <div class="canopy" ng-class="{ editing : editing }" style="">
      <div class="small-12 medium-10 large-6 small-centered columns member-info-wrapper" ng-cloak ng-show="profileUser">
        <div class="row">
          <div ng-if="cropNotSet && profileId === userId" class="small-12 columns set-crop">
            <h2>Success!</h2>
            <p><%= t('.show_you_around') %>
            </p>
            <p>
            <%= t('.this_is_your_member_profile_page') %>
            </p>
          </div>
          <form class="set-crop" ng-show="editing">
            <div class="row collapse">
              <div class="columns small-4">
                <label class="right inline">
                <%= t('.what_is_your_favorite_crop') %>
                </label>
              </div>
              <div class="columns small-6">
                <div crop-search
                  loading-crops-text="'<%= t('crop_searches.show.loading_crops') %>'"
                  crop-on-select="setFavoriteCrop"
                  clear-crop-selection="clearCropSelection">
                  </div>
              </div>


            </div>
          </form>
          <div ng-if="!editing" class="small-12 medium-4 columns">
            <!-- Make this a thing -->
            <div class="member-picture"
              style="background-image: url({{ profileUser.user_setting.pictures[0].medium_url || '/assets/baren_field.jpg' }})">
            </div>
          </div>
          <div ng-if="!editing" class="small-12 medium-8 columns member-infos">
            <h2><%= @user.display_name %></h2>
            <h5><%= @user.user_setting.location %></h5>

            <!-- Make this a user_setting and link_to crop page
            <h5>Favorite Crop: Blueberries</h5> -->

            <!-- Make this real
            <h5>Growing Practices: Organic</h5> -->
          </div>
        </div>
      </div>
      <!-- <%= link_to t('.application.edit_profile'), users_edit_path, class: 'tiny button secondary' %>
      <button class="button tiny secondary" ng-click="editing = !editing"><%= t('.edit_favorite_crop') %></button> -->
    </div>
  </div>

  <div class="row wide-row member-content">
    <!-- Sub header for mobile (replaces sidebar) TODO: Make it real
    <div class="small-12 show-for-small-only columns profile-sub-header">
      <ul>
        <li>
          <h4 class="number">4</h4>
          <p class="attribute">badges</p>
        </li>
        <li>
          <h4 class="number">22</h4>
          <p class="attribute">followers</p>
        </li>
        <li>
          <h4 class="number">68</h4>
          <p class="attribute">following</p>
        </li>
      </ul>
    </div> -->

    <!-- Sidebar for medium and up screens -->
    <div class="medium-4 large-3 show-for-medium-up columns profile-sidebar">
      <% if current_user == @user %>
        <%= link_to t('.application.edit_profile'), users_edit_path, class: 'tiny button secondary' %>
        <button class="button tiny secondary" ng-click="editing = !editing"><%= t('.edit_favorite_crop') %></button>

        <p class="member ">
          <%= t('.member_profile_intro') %>
        </p>

        <ul>
          <li>
            Units: {{ profileUser.user_setting.units }}
          </li>
          <!-- <li>
            Mailing List: {{ profileUser.mailing_list }}
          </li>
          <li>
            Help List: {{ profileUser.help_list }}
          </li> -->
          <!-- <li>
            Years Experience: {{ profileUser.user_setting.years_experience }}
          </li> -->
        </ul>
      <% end %>
      <%= render 'users/show/badges' %>
      <%#= render 'users/followers' %>
      <%#= render 'users/following' %>

    </div>

    <div class="small-12 medium-8 large-9 columns" ng-cloak>

      <!-- Member's Guides -->
      <div class="small-12 columns section">
        <%= render 'users/show/guides' %>
      </div>

      <!-- Member's Gardens -->
      <div class="small-12 columns section">
        <%= render 'users/show/gardens' %>
      </div>

      <!-- Member's Organizations TODO: everything
      <div class="small-12 columns section">
        <%= render 'users/show/organizations' %>
      </div> -->

      <div class="small-12 columns section">
        <% if @user == current_user %>
        Manage <%= link_to t('application.user_settings'), edit_user_registration_path %>
        <% end %>
      </div>

    </div>
  </div>
</div>

<% content_for(:end_js) do %>
  <%= javascript_tag "var USER_ID = '#{current_user ? current_user.id : nil}';" %>
  <%= javascript_tag "var PROFILE_ID = '#{@user ? @user.id : nil}';" %>
  <%= javascript_include_tag 'users/gardens' %>
  <%= javascript_include_tag 'users/show' %>
  <%= javascript_include_tag "search" %>
<% end %>