config/routes.rb
OpenFarm::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
      registrations: "registrations",
      confirmations: "confirmations"
    }

  scope '(:locale)', locale: /en|nl/ do
    root to: 'homes#show'
    post '(:locale)/crop_search' => 'crop_searches#search',
         as: :crop_search_via_post
    get '(:locale)/crop_search' => 'crop_searches#search',
        as: :crop_search_via_get

    devise_scope :users do
      get 'users/gardens' => 'users#gardens'
      get 'users/finish' => 'users#finish'
      get 'users/edit' => 'users#edit'
      put 'users' => 'users#update'
    end
    resources :users
    resources :crops
    resources :guides
    resources :stages
    resources :requirements
    resources :gardens
  end

  get 'announcements/hide', to: 'announcements#hide'

  namespace :api, defaults: {format: 'json'} do
    get '/aws/s3_access_token' => 'aws#s3_access_token'
    post '/local/upload_file' => 'file_upload#upload_file'

    namespace :v1 do
      get '/progress/pictures/:obj_type/:obj_id' => 'progress_job#show'

      resources :crops, only: [:create, :index, :show, :update] do
        resources :pictures, only: [:index, :show]
      end
      resources :tags, only: :index do
        collection do
          get '/:query', action: :index
        end
      end
      resources :guides, only: [:create, :show, :update, :destroy]
      resources :users, only: [:show, :update] do
        resources :gardens, only: [:index]
        resources :compatibility_score, only: [:show]
      end
      resources :gardens, only: [:create, :show, :update, :destroy] do
        resources :garden_crops, only: [:index,
                                        :show,
                                        :create,
                                        :update,
                                        :destroy]
      end
      resources :detail_options, only: [:index]
      resources :stage_options, only: [:index]
      resources :stage_action_options, only: [:index]
      resources :stages, only: [:create, :show, :update, :destroy] do
        resources :pictures,
                  only: [:index],
                  controller: 'stages',
                  action: 'pictures'
        resources :stage_actions,
                  only: [:index, :destroy]
                  # controller: 'stages',
                  # action: 'stage_actions'
      end

      resources :tokens, path: 'token', only: [:create] do
        collection do
          delete :destroy
        end
      end
    end
  end

  get '/:locale' => 'homes#show'
end

app/views/shared/_alerts.html.erb
<% if resource.errors.any? %>
  <div class="alert-box alert radius" data-alert="">
    <ul>
    <% resource.errors.full_messages.each do |full_message| %>
      <li><%= full_message %></li>
    <% end %>
    </ul>
    <a class="close" href="#">×</a>
  </div>
<% end %>

app/views/shared/_crop_form.html.erb
<%= form_for @crop do |f| %>
	<%= f.label :name, 'Crop Name' %>
	<%= f.text_field :name %>
	
	<%= f.label :binomial_name, 'Binomial Name' %>
	<%= f.text_field :binomial_name %>
	
	<%= f.label :description, 'Description' %>
	<%= f.text_area :description %>
	
	<%= f.label :sun_requirements, 'Sun Requirements' %>
	<%= f.text_field :sun_requirements %>
	
	<%= f.label :sowing_method, 'Sowing Method' %>
	<%= f.text_field :sowing_method %>
	
	<%= f.label :spread, 'Spread' %>
	<%= f.text_field :spread %>
	
	<%= f.label :days_to_maturity, 'Days to Maturity' %>
	<%= f.text_field :days_to_maturity %>
	
	<%= f.label :row_spacing, 'Row Spacing' %>
	<%= f.text_field :row_spacing %>
	
	<%= f.label :height, 'Height' %>
	<%= f.text_field :height %>
	
	<%= f.submit %>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
    <div class="row">
      <div class="about columns medium-3 small-12">
        <h3> Openfarm </h3>

        <%= link_to(t('meta.about'), page_path('about')) %>
        <%= link_to(t('meta.faq'), page_path('faq')) %>
        <%= link_to(t('meta.blog'), 'http://blog.openfarm.cc') %>
      </div>

      <div class="contribute columns medium-3 small-12">
        <h3> Contribute </h3>

        <%= link_to(t('meta.getting_started'), 'https://github.com/openfarmcc/OpenFarm/#development') %>

        <%= link_to(t('meta.slack'), 'https://goo.gl/forms/ATCZcU6Ohsy57wuI3') %>
        <%= link_to(t('meta.code_of_conduct'),page_path('code_of_conduct')) %>
      </div>

      <div class="legal columns medium-3 small-12">
        <h3> Openfarmers </h3>

        <%= link_to(t('meta.how_it_works'), '/en#how-it-works') %>
        <%= link_to(t('meta.ask_questions'), 'https://goo.gl/forms/ATCZcU6Ohsy57wuI3') %>


      </div>

      <div class="contact columns medium-3 small-12">
        <h3> Stay in touch </h3>
        <%= link_to(icon('fab', 'facebook-f'), 'https://www.facebook.com/OpenFarmCC/', class: 'social') %>
        <%= link_to(icon('fab', 'twitter'), 'https://twitter.com/openfarmcc/', class: 'social') %>
        <%= link_to(icon('fab', 'github'), 'https://github.com/OpenFarmCC/openfarm/', class: 'social') %>
        <%= link_to(icon('fa', 'envelope'), page_path('contact'), class: 'social') %>
        <%= link_to(icon('fab', 'slack'), 'http://slack.openfarm.cc/', class: 'social') %>

        <form action="//openfarm.us8.list-manage.com/subscribe/post?u=d41f97f612d606f032a884227&amp;id=8b8c94b1c5" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate class="">
          <label for="mce-EMAIL">Newsletter:
          </label>
          <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
          <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
          <div style="position: absolute; left: -5000px;"><input type="text" name="b_d41f97f612d606f032a884227_8b8c94b1c5" tabindex="-1" value=""></div>
          <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
        </form>
      </div>
    </div>
    <div class="row logo-and-terms">
      <h1>Openfarm</h1>
      <p><%= link_to(t('meta.tos'),page_path('tos')) %> &amp; <%= link_to(t('meta.privacy'), page_path('privacy')) %>
      </p>
    </div>
</footer>

app/views/shared/_header_links.html.erb
  <%= link_to t('application.create_guide'), new_guide_path, class: 'gray-to-black-link' %>

  <%= link_to t('application.my_profile'), user_path(current_user), class: 'gray-to-black-link' %>
  <%= link_to t('application.user_settings'), edit_user_registration_path, class: 'gray-to-black-link' %>

  <%= link_to(t("application.log_out"), destroy_user_session_path, method: :delete, class: 'gray-to-black-link', id: 'logout') %>