config/routes.rb
OpenFarm::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
      registrations: "registrations",
      confirmations: "confirmations"
    }

  scope '(:locale)', locale: /en|nl/ do
    root to: 'homes#show'
    post '(:locale)/crop_search' => 'crop_searches#search',
         as: :crop_search_via_post
    get '(:locale)/crop_search' => 'crop_searches#search',
        as: :crop_search_via_get

    devise_scope :users do
      get 'users/gardens' => 'users#gardens'
      get 'users/finish' => 'users#finish'
      get 'users/edit' => 'users#edit'
      put 'users' => 'users#update'
    end
    resources :users
    resources :crops
    resources :guides
    resources :stages
    resources :requirements
    resources :gardens
  end

  get 'announcements/hide', to: 'announcements#hide'

  namespace :api, defaults: {format: 'json'} do
    get '/aws/s3_access_token' => 'aws#s3_access_token'
    post '/local/upload_file' => 'file_upload#upload_file'

    namespace :v1 do
      get '/progress/pictures/:obj_type/:obj_id' => 'progress_job#show'

      resources :crops, only: [:create, :index, :show, :update] do
        resources :pictures, only: [:index, :show]
      end
      resources :tags, only: :index do
        collection do
          get '/:query', action: :index
        end
      end
      resources :guides, only: [:create, :show, :update, :destroy]
      resources :users, only: [:show, :update] do
        resources :gardens, only: [:index]
        resources :compatibility_score, only: [:show]
      end
      resources :gardens, only: [:create, :show, :update, :destroy] do
        resources :garden_crops, only: [:index,
                                        :show,
                                        :create,
                                        :update,
                                        :destroy]
      end
      resources :detail_options, only: [:index]
      resources :stage_options, only: [:index]
      resources :stage_action_options, only: [:index]
      resources :stages, only: [:create, :show, :update, :destroy] do
        resources :pictures,
                  only: [:index],
                  controller: 'stages',
                  action: 'pictures'
        resources :stage_actions,
                  only: [:index, :destroy]
                  # controller: 'stages',
                  # action: 'stage_actions'
      end

      resources :tokens, path: 'token', only: [:create] do
        collection do
          delete :destroy
        end
      end
    end
  end

  get '/:locale' => 'homes#show'
end

app/models/crop.rb
# frozen_string_literal: true

# a Crop is the basic searchable unit within OpenFarm. The term 'plant' was
# avoided to stay generic (ex: edible fungi).
class Crop
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  include Mongoid::Taggable

  searchkick

  field :impressions_field, default: 0, type: Integer

  has_many :guides
  field :guides_count, type: Integer, default: 0
  field :svg_icon
  validates_length_of :svg_icon,
                      minimum: 11,
                      maximum: 75.kilobytes,
                      # Size of empty "<svg></svg>" tag.
                      # 3x larger than largest icon.
                      allow_blank: true
  field :description
  belongs_to :crop_data_source
  field :sun_requirements
  field :sowing_method
  field :spread, type: Integer
  field :growing_degree_days, type: Integer
  field :minimum_temperature, type: Integer # In Celcius
  field :row_spacing, type: Integer
  field :height, type: Integer

  # Naming. This is tricky.
  # See https://github.com/openfarmcc/OpenFarm/issues/641
  field :binomial_name

  field :genus
  field :species

  field :taxon, type: String
  validates_inclusion_of :taxon,
                         in: %w[Species Genus Family Order Class Phylum Kingdom Domain Life Other],
                         message: '%{value} is not a valid taxon',
                         allow_nil: true

  field :cultivar_name

  field :name
  field :common_names, type: Array
  validates :name, presence: true

  has_and_belongs_to_many :companions, class_name: 'Crop', inverse_of: :companions

  field :processing_pictures, type: Integer, default: 0
  embeds_many :pictures, cascade_callbacks: true, as: :photographic
  accepts_nested_attributes_for :pictures

  slug :name

  after_save :backlink_companion_crops

  def search_data
    as_json only: %i[name common_names binomial_name description guides_count]
  end

  def main_image_path(args = {})
    if pictures.present?
      pictures.first.attachment.url(args[:size] || :large)
    else
      # WARNING! MVC VIOLATION AHEAD!!!! =======================================
      # The fact that we are using polymorphic embedded documents means we would
      # need to add an extra build step to populate S3 and then add conditional
      # logic to figure out which class its embedded in to return the correct
      # URL.

      # If someone reading this has a better idea, I'd love to hear it. In the
      # meantime, I'm willing to look the other way and violate MVC in favor of
      # having less code to maintain. The current solution lets us keep the file
      # in source control instead of expecting the developer to upload it to an
      # S3 bucket when setting up new boxes.
      if args[:front_page]
        ActionController::Base.helpers.asset_path('baren_field_310x310.jpg')
      else
        ActionController::Base.helpers.asset_path('baren_field_square.jpg')
      end
    end
  end

  # This is nasty, but it's because mongoid doesn't do
  # Has And Belongs To Many relationships that point to
  # self very well.
  def backlink_companion_crops
    # clean up what was
    if companion_ids_was.present?
      companion_ids_was.each do |oldcomp|
        oldcomp = Crop.find(oldcomp)
        # We explicitely skip this backlink validation here
        # again otherwise we'll loop indefinitely.
        Crop.skip_callback(:save, :after, :backlink_companion_crops)
        oldcomp.companions.delete(self)
        Crop.set_callback(:save, :after, :backlink_companion_crops)
      end
    end

    # now link these things
    if companions.present?
      companions.each do |new_companion|
        new_companions = new_companion.companions + [self]
        # We explicitely skip this backlink validation here
        # again otherwise we'll loop indefinitely.
        Crop.skip_callback(:save, :after, :backlink_companion_crops)
        new_companion.set(companions: new_companions.uniq)
        Crop.set_callback(:save, :after, :backlink_companion_crops)
      end
    end
  end
end

app/controllers/api/v1/crops_controller.rb
# frozen_string_literal: true

class Api::V1::CropsController < Api::V1::BaseController
  skip_before_action :authenticate_from_token!, only: %i[index show]

  def index
    render json: should_perform_search? ? search_result : empty_search_result
  end

  def show
    crop = Crop.find(raw_params[:id])
    render json: serialize_model(crop, include: %w[pictures companions])
  end

  def create
    @outcome = Crops::CreateCrop.run(raw_params[:data], user: current_user)
    respond_with_mutation(:ok, include: %w[pictures])
  end

  def update
    # According to JSON-API Params must be structured like this:
    # {
    #   'data': {
    #     'type': 'crops',
    #     'id': '<id>',
    #     'attributes': {
    #     },
    #   }
    # }
    @outcome = Crops::UpdateCrop.run(raw_params[:data], user: current_user, id: raw_params[:id])
    respond_with_mutation(:ok, include: %w[pictures])
  end

  private

  def crops
    @crops ||=
      Crop.search(
        raw_params[:filter],
        limit: 25,
        operator: 'or',
        misspellings: {
          # partial: true,
          distance: 1
        },
        fields: %w[name^20 common_names^10 binomial_name^10 description],
        boost_by: %i[guides_count]
      )
  end

  def should_perform_search?
    raw_params[:filter].present? && (raw_params[:filter].length > 2)
  end

  def empty_search_result
    p = raw_params[:page]
    model = p ? Crop.page(p) : Crop.none
    serialize_models(model)
  end

  def search_result
    serialize_models(crops, include: %w[pictures])
  end
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  after_action :verify_authorized, except: [:index, :show]

  def index
    @crops = Crop.all
    redirect_to(controller: "crop_searches", action: "search")
  end

  def new
    @crop = Crop.new(name: raw_params[:name])
    authorize @crop
  end

  def show
    @crop = Crop.find(raw_params[:id])
    unsorted_guides =
      @crop.guides.order(impressionist_count: :asc).limit(10).to_a || []
    @guides = Guide.sorted_for_user(unsorted_guides, current_user)
    respond_to do |format|
      format.html
      format.svg do
        send_data((@crop.svg_icon || DEFAULT_ICON),
                  type: 'image/svg+xml', disposition: 'inline')
      end
    end
  end

  def create
    @crop = Crop.new(crops_params)
    authorize @crop
    if @crop.save && raw_params[:crop][:source] == "guide"
      redirect_to(controller: "guides", action: "new",
                  crop_id: @crop.id)
    elsif @crop.save
      redirect_to(controller: "crops", action: "show",
                  id: @crop.id)
    else
      render :new
    end
  end

  def edit
    @crop = Crop.find(raw_params[:id])
    authorize @crop
  end

  def update
    @crop = Crop.find(raw_params[:id])
    authorize @crop
    # TODO: Hacky hack is hacky.
    # Move the images in crop to be in images.
    # It's too nested if in crops.
    attributes = raw_params[:attributes]
    raw_params[:images] = attributes[:images] ? [attributes[:images]] : []
    @outcome = Crops::UpdateCrop.run(raw_params,
                                     attributes: attributes,
                                     id: raw_params[:id],
                                     user: current_user)
    if @outcome.success?
      @crop.reload
      redirect_to(action: "show", id: @crop.id)
    else
      flash[:alert] = @outcome.errors.message_list
      @crop.reload
      render :edit
    end
  end

  private

  # TODO: This should be moved to a migration.
  def crops_params
    params.require(:crop).permit(:name, :binomial_name, :description,
                                 :sun_requirements, :sowing_method, :spread, :days_to_maturity,
                                 :row_spacing, :height)
  end
end

app/views/crops/_crop_form.html.erb
<div class="crop-manipulation"
    ng-controller="cropCtrl">

  <div alerts ng-model="alerts"></div>

  <div class="row">
    <div class="small-8 medium-10 small-12 small-centered columns">

      <h1>
        <% if @crop.name %>
          Edit <%= link_to @crop.name, @crop %>
        <% else %>
          Add a new crop
        <% end %>
      </h1>
      <p><span class="form-required">* Required</span></p>
    </div>
  </div>
  <form name="cropForm">
    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="crop_name">OpenFarm Crop Name <span class="form-required">*</span></label>
      </div>
      <div class="columns small-8 medium-8">
        <input data-ng-model="crop.name"
               id="crop_name"
               name="crop[name]"
               type="text"
               required/>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="crop_name">Common Names</label>
      </div>
      <div class="columns small-8 medium-8">
        <small>Comma Separated or New Lines</small>
        <textarea data-ng-model="crop.common_names"
               id="crop_common_names"
               name="crop[common_names]"
               type="text"></textarea>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="binomial_name">Binomial Name</label>
      </div>
      <div class="columns small-8 medium-8">
        <input data-ng-model="crop.binomial_name"
               id="crop_binomial_name"
               name="crop[binomial_name]"
               type="text"/>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="taxon"><%= t('crops.edit.taxon') %></label>
      </div>
      <div class="columns small-8 medium-8">
            <select ng-model="crop.taxon"
                    id="crop_taxon"
                    name="crop[taxon]">
              <option value="Species"><%= t('crops.edit.species') %></option>
              <option value="Genus"><%= t('crops.edit.genus') %></option>
              <option value="Family"><%= t('crops.edit.family') %></option>
              <option value="Order"><%= t('crops.edit.order') %></option>
              <option value="Class"><%= t('crops.edit.class') %></option>
              <option value="Phylum"><%= t('crops.edit.phylum') %></option>
              <option value="Kingdom"><%= t('crops.edit.kingdom') %></option>
              <option value="Domain"><%= t('crops.edit.domain') %></option>
              <option value="Life"><%= t('crops.edit.life') %></option>
              <option value="Other"><%= t('crops.edit.other') %></option>
            </select>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="description"><%= t('crops.edit.companions') %>:</label>
      </div>

      <div class="columns small-8 medium-8 tags">
        <ul class="companions tag-list">
          <li ng-repeat="crop in crop.companions track by crop.slug" class="tag-item">
            {{ crop.name }}
            <i class="delete fa fa-times"
              ng-click="removeCompanionCrop($index)">
            </i>
          </li>
        </ul>
        <div crop-search
          loading-crops-text="'<%= t('crop_searches.show.loading_crops') %>'"
          crop-on-select="addCompanionCrop"
          required="iscompanionrequired"
          does-not-have-button="true">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="description"><%= t('crops.edit.description') %></label>
      </div>
      <div class="columns small-8 medium-8">
        <textarea ng-model="crop.description"
                  id="crop_description"
                  name="crop[description]"
                  ></textarea>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="sun_requirements">Sun Requirements</label>
      </div>
      <div class="columns small-8 medium-8">
            <select ng-model="crop.sun_requirements"
                    id="crop_sun_requirements"
                    name="crop[sun_requirements]">
              <option value="Full Sun"><%= t('edit.full_sun') %></option>
              <option value="Partial Sun"><%= t('edit.partial_sun') %></option>
              <option value="Full Shade"><%= t('edit.full_shade') %></option>
            </select>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="crop_growing_degree_days">Growing Degree Days</label>
      </div>
      <div class="columns small-8 medium-8">
        <input data-ng-model="crop.growing_degree_days"
               id="crop_growing_degree_days"
               name="crop[growing_degree_days]"
               type="number"/>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="sowing_method">Sowing Method</label>
      </div>
      <div class="columns small-8 medium-8">
        <input data-ng-model="crop.sowing_method"
               id="crop_sowing_method"
               name="crop[sowing_method]"
               type="text"/>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="spread">Spread (diameter)</label>
      </div>
      <div class="columns small-8 medium-8">
        <div class="row collapse">
          <div class="columns small-10">
            <input data-ng-model="crop.spread"
                   id="crop_spread"
                   name="crop[spread]"
                  type="number"/>
          </div>
          <div class="columns small-2">
            <span class="postfix">cm</small>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="row_spacing">Row Spacing</label>
      </div>
      <div class="columns small-8 medium-8">
        <div class="row collapse">
          <div class="columns small-10">
            <input data-ng-model="crop.row_spacing"
                   id="crop_row_spacing"
                   name="crop[row_spacing]"
                   type="number"/>
          </div>
          <div class="columns small-2">
            <span class="postfix">cm</small>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label class="right" for="height">Height</label>
      </div>
      <div class="columns small-8 medium-8">
        <div class="row collapse">
          <div class="columns small-10">
            <input data-ng-model="crop.height"
                   id="crop_height"
                   name="crop[height]"
                   type="number"/>
          </div>
          <div class="columns small-2">
            <span class="postfix">cm</small>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label for="crop[images]" class="right">Manage images</label>
      </div>
      <of-images-upload
        class="columns small-8 medium-8"
        item="crop"
        images-key="'pictures'"
        item-type="'crop'">
      </of-images-upload>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label for="crop[icon]" class="right">Manage icon</label>
      </div>
      <div class="columns small-8 medium-8">
        <div class="crop-icon-wrapper">
          <%= image_tag crop_path(@crop, format: :svg), alt: @crop.name %>
        </div>
        <svg-button on-change="addSvg($svg)">
        </svg-button>
      </div>
    </div>

    <div class="row">
      <div class="columns small-4 medium-4">
        <label for="crop[tags]" class="right">Keywords</label>
      </div>
      <div class="columns small-8 medium-8">
        <tags-input
          ng-model="crop.tags_array"
          class="keywords"
          name="crop[tags]">
          <auto-complete source="loadTags($query)"></auto-complete>
        </tags-input>
      </div>
    </div>

    <div class="row form-buttons">
      <div class="columns small-12 medium-12">
        <span class="right">
          <i ng-if="crop.sending"
            class="fa fa-spinner fa-spin loading-button"></i>
          <input class="button small"
            type="submit"
            name="commit"
            value="<%= t('crops.edit.save_crop') %>"
            data-disable-with="Saving..."
            ng-disabled="crop.sending || cropForm.$invalid"
            ng-click="submitForm()"/>
        </span>
      </div>
    </div>
  </form>
</div>

app/views/crops/_exists_or_edit.html.erb
<% if local_assigns[:unit_type] == 'distance' && obj %>
  <%= obj %> <small class="measurement-unit"><%= I18n.t('measurements.centimeters', count: obj) %></small>
<% elsif local_assigns[:unit_type] == 'time' && obj %>
  <%= obj %> <small class="measurement-unit"><%= I18n.t('measurements.time.days', count: obj) %></small>
<% elsif obj != '' %>
  <%= obj %>
<% else %>
  <small><%= link_to(icon('fa', 'edit') + " " + t('crops.add_this_information'), {action: 'edit'}) %></small>
<% end %>

app/views/crops/edit.html.erb
<%= render 'crops/crop_form' %>

app/views/crops/new.html.erb
<%= render 'crops/crop_form' %>

app/views/crops/show.html.erb
<%= content_for(:description) do %><%= truncate(@crop.description, length: 80, separator: ' ') %><% end %>
<%= content_for(:social_image) do %><%= image_url(@crop.main_image_path) %><% end %>
<%= content_for(:keywords) do %><% if @crop.common_names %><%= @crop.common_names.join(', ') %><% end %>, <%= @crop.name %>, <%= @crop.binomial_name %><% end %>
<%= content_for(:title) do %> - <%= @crop.name %><% end %>

<div class="crop-page row wide-row"
     data-equalizer
     ng-controller="showCropCtrl"
     ng-cloak>
  <div data-equalizer-watch class="crop-info-container columns medium-6 small-12">
    <div class="crop-hero" style="background-image: url('<%= @crop.main_image_path.sub(/(https|http):/, '') %>')">
      <h1 class="crop-name text-center"><%= @crop.name %></h1>
      <% if current_user %>
        <%= link_to(icon('fa', 'edit') + " " + t('crops.edit_crop'), {action: 'edit'}, class: 'edit-link button secondary tiny') %>
          <div add-to-gardens
              crop-object="crop"
              object-type="'crop'"
              user="currentUser">
            </div>
      <% end %>

    </div>
    <table class="crop">
        <tbody>
        <tr>
          <td colspan="2">
          <a of-lightbox-modal ng-repeat="picture in crop.pictures"
            thumbnail-url="{{picture.small_url}}" display-url="{{picture.image_url}}">
          </a>
          <span ng-show="processingPictures" class="still-uploading-crop-images">
            <i class="fa fa-spin fa-spinner"></i>
            processing images...
          </span>
          </td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.tags') %></td>
          <td><%= @crop.tags_array.join(', ')%></td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.binomial_name') %></td>
          <td><%= render partial: '/crops/exists_or_edit', locals: {obj: @crop.binomial_name} %></td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.taxon') %></td>
          <td><%= render partial: '/crops/exists_or_edit', locals: {obj: @crop.taxon} %></td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.description') %></td>
          <td><%= render partial: '/crops/exists_or_edit', locals: {obj: @crop.description} %></td>
        </tr>
        <tr>
          <td>
            <%= I18n.t('crops.companions') %>
          </td>
          <td>
            <% @crop.companions.all.each do |comp| %>
              <%= link_to comp do %>
                <div class="crop-icon-wrapper">
                  <%= image_tag crop_path(comp, format: :svg), alt: comp.name %>
                </div>
                <%= comp.name %>
              <% end %>
            <% end  %></td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.sun_requirements') %></td>
          <td><%= render partial: '/crops/exists_or_edit', locals: {obj: @crop.sun_requirements} %></td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.growing_degree_days') %></td>
          <td><%= render partial: '/crops/exists_or_edit', locals: {obj: @crop.growing_degree_days, unit_type: 'time'} %></td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.sowing_method') %></td>
          <td>
          <%= render partial: '/crops/exists_or_edit', locals: {obj: @crop.sowing_method} %></td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.spread') %></td>
          <td>
            <%= render partial: '/crops/exists_or_edit', locals: {obj: @crop.spread, unit_type: 'distance'} %>
          </td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.row_spacing') %></td>
          <td>
            <%= render partial: '/crops/exists_or_edit', locals: {obj: @crop.row_spacing, unit_type: 'distance'} %>
          </td>
        </tr>
        <tr>
          <td><%= I18n.t('crops.height') %></td>
          <td>
            <%= render partial: '/crops/exists_or_edit', locals: {obj: @crop.height, unit_type: 'distance'} %>
          </td>
        </tr>
        </tbody>
    </table>
  </div>
  <div data-equalizer-watch class="guide-results-container columns medium-6 small-12">
    <h2 class="text-center"><%= @guides.blank? ? "There are no guides for this crop yet" : "Guides for this crop" %></h2>
    <%= link_to new_guide_path(:crop_id => @crop.id), :class => "add-guide" do %>
      <p><i class="fa fa-plus symbol-add"></i>Make your own!</p>
    <%end%>
    <%= render partial: '/guides/guide_results_list', object: @guides %>
  </div>
</div>

<% content_for(:end_js) do %>
<%= javascript_tag "var USER_ID = '#{current_user ? current_user.id : nil}';" %>
<% end %>